### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by gassio** [eellak/business-plan-tool#193]

**Comment by ggcarlosr** [comment]
Hello brother, I am a graphic designer and I can help you for free with the design of the logo for your app.

**Comment by kellyMalerou** [comment]
Hello @ggcarlosr and thank you for your interest!
I started to design some simple logos and we decided with the rest of the team members that the following could be an example of what we wish, in the first instance, for our application. Generally, we prefer more minimal designs. Any idea, suggestion or even a design is welcome and desirable :) 

![logo4](https://user-images.githubusercontent.com/35432179/40200979-61646b3c-5a26-11e8-9b0f-6e2610ac914e.jpg)
![logo7](https://user-images.githubusercontent.com/35432179/40200982-65afcb78-5a26-11e8-8047-1bf45b5b64d8.jpg)

**Comment by ggcarlosr** [comment]
Hello Friend, here again with some ideas that I have made I hope you like and can meet your expectations, let me know your suggestions for me is very important to always be according to your tastes...

![bp-tool](https://user-images.githubusercontent.com/37964430/40282287-1e0c6120-5c3b-11e8-9ffa-d5d2275b314e.png)

**Comment by kellyMalerou** [comment]
Hi @ggcarlosr !
We liked your designs a lot! :) 
Maybe an ideal design for us is in the middle of the first one i posted at my previous comment and the second one of your designs.

What we would like more, if you could, is a color change in order to match with the rest of application so that we have consistency in our ui design.
I attach here a document with the Hex color codes used, 
[Color details.txt](https://github.com/eellak/business-plan-tool/files/2038275/Color.details.txt)
you can check them and adjust the colors to them however you like, maybe not so intense tones at the "b" (like your first design).
Also, any idea for different background of the logo is desirable!

Thank you a lot once again!

**Comment by ggcarlosr** [comment]
brother thank you for answering, checking the txt color is the most suited is this that I show, and I think it looks great, less strong colors that plantie. I hope you can take this as a definite option for your project. Thank you. 


![bp-tool](https://user-images.githubusercontent.com/37964430/40572368-66b17cda-6078-11e8-895e-88787fbebea0.png)

**Comment by gassio** [comment]
@ggcarlosr nice job!
Could you please send us the transparent logo in order to use it? 
Also, could you sent us in editable format (psd, ai)?

**Comment by ggcarlosr** [comment]
Hi I created a request for extraction with some transparent files of the logo, just like here I will leave a link with the entire package of the Editable Logo. Notify me when the logo is available at https://bptool.herokuapp.com I am anxious to see the work done there. Thank you for the opportunity provided. 
[Link Edit Files Here](https://drive.google.com/open?id=1PuDYQGyTW-th0mEQLxWnaDs4nZnLwTRo)
